### ISSUE TITLE
Wondering why ZNetZigBeeS2 is not supported.

### ISSUE THREAD

**Issue by PaulNoto** [jefffhaynes/XBee#10]
Checking serial ports: COM4
Failed to open COM4 with ZNetZigBeeS2 not supported.

These are the previous XBees that have reached End Of Life. MFPN: XB24-Z7WIT-004. I was just wondering why they are not supported. Not a problem. However, I have some spares I would like to be able to use and I'm guessing other people are in the same boat.

**Comment by jefffhaynes** [comment]
Do you know what the hardware version is?






On Sun, Apr 24, 2016 at 1:52 PM -0700, "PaulNoto" <notifications@github.com> wrote:












Checking serial ports: COM4

Failed to open COM4 with ZNetZigBeeS2 not supported.



These are the previous XBees that have reached End Of Life. MFPN: XB24-Z7WIT-004. I was just wondering why they are not supported. Not a problem. However, I have some spares I would like to be able to use and I'm guessing other people are in the same boat.

**Comment by PaulNoto** [comment]
Hardware Version is  194B

**Comment by PaulNoto** [comment]
I checked 3 versions that I Have:
194B is the Hardware Version for Wire and U.FL Antenna.
1943 is for PCB Antenna.
