### ISSUE TITLE
Not Receiveing Samples from my nodes

### ISSUE THREAD

**Issue by PaulNoto** [jefffhaynes/XBee#13]
Not receiving samples from my nodes after the last update to the XBee and Serializer Libraries. I was reading your comments from my last issue and it seems like you already know about this. Please let me know if there is a known issue or if I need to figure out what I didn't get updated correctly on my end.

**Comment by jefffhaynes** [comment]
Actually I was expecting it to work now. Are you still seeing the same behavior with the null field?






On Mon, Apr 25, 2016 at 12:53 PM -0700, "PaulNoto" <notifications@github.com> wrote:












Not receiving samples from my nodes after the last update to the XBee and Serializer Libraries. I was reading your comments from my last issue and it seem like you already know about this. Please let me know if there is a known issue or if I need to figure out what I didn't get updated correctly on my end.

**Comment by PaulNoto** [comment]
No samples get received from any of my nodes. I can still send output pin commands like Turn the light On / Off.

**Comment by PaulNoto** [comment]
I will re-check everything when I get home tonight, if you think everything should be working.

**Comment by jefffhaynes** [comment]
It appeared to be working when I tested it but I'll go over it again. 






On Mon, Apr 25, 2016 at 5:06 PM -0700, "PaulNoto" <notifications@github.com> wrote:












I will re-check everything when I get home tonight, if you think everything should be working.

**Comment by PaulNoto** [comment]
OK, let me know what you find.

**Comment by jefffhaynes** [comment]
Everything looks right.  I did just push 2.2.2 with a minor fix but I don't
think it's what you're seeing.  Can you give me a little more info on the
symptoms?  I currently have a node sending samples once per second.  I've
tried a mix of digital and analog samples and everything seems fine.

Can you confirm that you're on XBee 2.2.2 and BinarySerializer 4.7.2?  XBee
2.2.1 and above should have a dependency on 4.7.2 but maybe it isn't
getting updated for some reason.

Thanks


On Mon, Apr 25, 2016 at 8:09 PM, PaulNoto <notifications@github.com> wrote:

> OK, let me know what you find.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/XBee/issues/13#issuecomment-214568834>
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by PaulNoto** [comment]
It's Working. Samples are coming in and DigitalSampleState is with them. I downloaded your latest XBee Library and added the XBee Source to my project and did a Clean then Re-Build. When I Ran, everything was working. Maybe VS Got confused on my previous update.

Anyway, Thank you so much for all the help. I really appreciate what you have done by creating this library. Thank You, Thank You, Thank You...........

**Comment by jefffhaynes** [comment]
That's great, glad to hear it!  Please let me know if you run into any more
issues.

Cheers

On Mon, Apr 25, 2016 at 10:56 PM, PaulNoto <notifications@github.com> wrote:

> It's Working. Samples are coming in and DigitalSampleState is with them. I
> downloaded your latest XBee Library and added the XBee Source to my project
> and did a Clean then Re-Build. When I Ran, everything was working. Maybe VS
> Got confused on my previous update.
>
> Anyway, Thank you so much for all the help. I really appreciate what you
> have done by creating this library. Thank You, Thank You, Thank
> You...........
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/XBee/issues/13#issuecomment-214592595>
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by PaulNoto** [comment]
I will. The road ahead is still long.
