### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by GuillaumeB17** [jefffhaynes/XBee#18]

**Comment by jefffhaynes** [comment]
I don't think so but should be easy to add. Give me a day or so. 






On Wed, Jun 15, 2016 at 2:15 PM -0400, "GuillaumeB17" <notifications@github.com> wrote:












Hello,



I have a question about your lib. Is it possible to set or get PanID ?



Thank you in advance.

**Comment by GuillaumeB17** [comment]
It's good I found how to do this
Thank you
