### ISSUE TITLE
[FieldLength] for null string

### ISSUE THREAD

**Issue by abrasat** [jefffhaynes/XBee#2]
It seems that the reserved field length for a string is ignored if the string is null. If the string is empty, it works fine.

   [FieldLength(50)]
   [SerializeAs(Encoding = "ASCII")]
   public string Data { get; set; }

**Comment by jefffhaynes** [comment]
Thanks, was this meant to be against BinarySerializer or XBee?  If it's XBee, which class is this in?

**Comment by abrasat** [comment]
Sorry, was meant for the BinarySerializer. I will repost there, please remove the issue here.
