### ISSUE TITLE
Timeout XBee Series 2 Pro S5

### ISSUE THREAD

**Issue by fguiet** [jefffhaynes/XBee#32]
Hi mate, 

Try to get controller by issuing this statement on my XBee Series 2 Pro S5
var controller = await XBeeController.FindAndOpenAsync(SerialPort.GetPortNames(), 115200);

but it keeps on throwing TimeoutException on this statement from class XBeeControllerBase :

if (await Task.WhenAny(taskCompletionSource.Task, delayTask).ConfigureAwait(false) !=
                taskCompletionSource.Task)
            {
                throw new TimeoutException();
            }

Got Hardware version correctly filled up...but address is always null (maybe it is the problem?)

Can you help?
Thank u
Fred

**Comment by jefffhaynes** [comment]
Hm not sure. I'll take a look as soon as I can.

________________________________

**Comment by fguiet** [comment]
Hey Jeff,

Thank for ya answer.

I added this line to XBeeControllerBase so my XBee Pro 5S get recognized 

Line about 560 : case HardwareVersion.XBeeProS5:
                    return new XBeeSeries2(this, HardwareVersion.XBeeProS2, address);

Add to say that my XBee is using API mode 2

and voila...

Fred

**Comment by jefffhaynes** [comment]
I'm not familiar with that model.  What value to you assign to HardwareVersion.XBeeProS5?

**Comment by fguiet** [comment]
Heya,

I set HardwareVersion.XBeeProS5 to 0x1D
I wanted to order more of that product but it is now obselete...so may be it is not worth adding this device to your great C# XBee API...I am currently using an old API (that is still working so...)

Fred
