### ISSUE TITLE
ATCommand for CB

### ISSUE THREAD

**Issue by scervellera** [jefffhaynes/XBee#40]
Hello Jeff,
I noticed that isn't present a command for CB (commisioning button). I would ask you if possibile to send custom AT command to local xBee or is mandattory have a specific function for single AT command.

Thank so much

Stefano

**Comment by jefffhaynes** [comment]
It’s not possible just because of the semantics of each command, especially with respect to the device model but I can take a look at it.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
Pushed in XBee.Core 1.5.7

**Comment by scervellera** [comment]
Great!!

Thank you Jeff!!!
