### ISSUE TITLE
RSSI Querying

### ISSUE THREAD

**Issue by PaulHeitkemper** [jefffhaynes/XBee#43]
Would like to be able to query each node for its RSSI. 

From my newbie's reading of various docs, I should be able to send a node the DB command, but this API restricts it to the XBeeCellular class. Why is that? 

I can give this a go once my hardware shipment comes in and is alive again, but that may be next week.

**Comment by jefffhaynes** [comment]
It shouldn't be limited to cellular.  Fixed in 1.5.9.  Thanks
