### ISSUE TITLE
How to Get into API Mode programmatically?

### ISSUE THREAD

**Issue by PaulHeitkemper** [jefffhaynes/XBee#45]
Seems like a bootstrapping problem. Is there a way to talk to a local XBee device via serial port to do what XCTU does to set API Mode?

**Comment by jefffhaynes** [comment]
Yeah I was thinking about this recently. It is a bootstrapping problem but I can work on it.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by PaulHeitkemper** [comment]
Is this the right answer? I won't be looking into it for several days.

https://www.digi.com/support/forum/66685/digimesh-how-to-enter-api-mode?show=66685#q66685

**Comment by jefffhaynes** [comment]
Yes, that’s how you enter it. I was trying to come up with a way to detect that it needed to be switched but maybe that doesn’t make sense. If it’s just a method call then that’s easy.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by PaulHeitkemper** [comment]
Can you just read the AP value to see if it is 0, or are you talking about something else? In the serial console in XCTU, I get the following:

+++OK

ATAP
1

**Comment by jefffhaynes** [comment]
Well I think that’s the rub. You can but do you read it with API mode or not?

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by PaulHeitkemper** [comment]
I was able to issue the following commands from the serial console inside XCTU.

+++OK
ATAP
0
ATAP1
OK
ATWR
OK
ATAP
1
ATAP0
OK
ATWR
OK

**Comment by jefffhaynes** [comment]
Gotcha.  Ok, that should work.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by jefffhaynes** [comment]
Are you ok if I just set API mode on controller open?  It's probably the easiest since after that the handlers take over and I can't easily inject textual AT commands

**Comment by PaulHeitkemper** [comment]
seems fine. I plan to use them all in API Mode anyway.

**Comment by jefffhaynes** [comment]
Done.  Core 1.6 will automatically switch controllers into API mode when opened.  However, note that it will not persist the settings.  Once in API mode you can use the normal Set/GetApiModeAsync methods to manage it along with WriteAsync().

**Comment by PaulHeitkemper** [comment]
Thanks!
