### ISSUE TITLE
cannot build the project...

### ISSUE THREAD

**Issue by fvarelie** [jefffhaynes/XBee#5]
Hi, I'm using vs 2015 and can't build the project. the error is unable to locate nuget.exe....

btw, is this api compatible with xbee xtend?

**Comment by jefffhaynes** [comment]
Sorry about that, I have been futzing with it lately in an effort to port it to .net core and I may have inadvertently checked something in. I'll look at it as soon as I can. 
I've never tested it against xtend so my guess is that it doesn't work but I'm also not really sure what the xtend api looks like. 






On Mon, Mar 28, 2016 at 4:11 AM -0700, "fvarelie" <notifications@github.com> wrote:












Hi, I'm using vs 2015 and can't build the project. the error is unable to locate nuget.exe....



btw, is this api compatible with xbee xtend?
