### ISSUE TITLE
Broadcast Message

### ISSUE THREAD

**Issue by koopermark** [jefffhaynes/XBee#56]
Hi, 
Is there a way to broadcast a message so all modules receive it?

I am using XTCU to send messages and picking them up by using controller.DataReceived but I would like to be able to do it the other way round.

Send from the PI to XTCU (multiple xbee's connected) using broadcast so that each Xbee would receive a message - I will then handle the message and send back a response.

Kind Regards

**Comment by koopermark** [comment]
Hi, 
Any information on this would be greatly appreciated, I would gladly send a donation if you can help.

**Comment by jefffhaynes** [comment]
Sorry I’ve been swamped but I believe there is an XBeeAddress.Broadcast value you can use.


________________________________

**Comment by koopermark** [comment]
No worries, on being busy ;-)

I am struggling to understand how to use it XBeeAddress.Broadcast after the following
`XBeeController controller = controllers.First();`

**Comment by jefffhaynes** [comment]
I think something like await controller.SendDataAsync, no?


________________________________

**Comment by koopermark** [comment]
I was trying `await controller.Local.TransmitDataAsync(Encoding.UTF8.GetBytes("Hello!"));`
but i seem to get Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.ni.dll

**Comment by jefffhaynes** [comment]
Hm. How are you getting controllers?


________________________________

**Comment by koopermark** [comment]
Like this

`namespace test
{

    public sealed class StartupTask : IBackgroundTask
    {

        private BackgroundTaskDeferral deferral;

        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            // 
            // TODO: Insert code to perform background work
            //
            // If you start any asynchronous methods here, prevent the task
            // from closing prematurely by using BackgroundTaskDeferral as
            // described in http://aka.ms/backgroundtaskdeferral
            //


            Debug.WriteLine("Starting Connection");
            deferral = taskInstance.GetDeferral();
            List<XBeeController> controllers = await XBeeController.FindControllersAsync(9600);
            XBeeController controller = controllers.First();
            Debug.WriteLine("Connection Done");

            await controller.Local.TransmitDataAsync(Encoding.UTF8.GetBytes("Hello!"));

        }
    }
}`

**Comment by jefffhaynes** [comment]
Looks right to me. That exception is fishy. It seems like a system device issue. Is there any message to go with it?


________________________________

**Comment by koopermark** [comment]
I will check and let you know in the morning. 
Thank you for your help.

**Comment by koopermark** [comment]
The error message I get is 
Can't send data to local device.

**Comment by jefffhaynes** [comment]
Oh of course. Maybe that should default to broadcast...

I guess there might not be a great way to broadcast right now, which is unfortunate. What happens if you do

await controller.GetNodeAsync(XBeeAddress.Broadcast, ... etc)

and then transmit data to that node?




________________________________

**Comment by koopermark** [comment]
I get - The name 'XBeeAddress' does not exist in the current context
If i change it to `await controller.GetNodeAsync(LongAddress.Broadcast);`

then I get - cannot convert from 'XBee.LongAddress' to 'XBee.NodeAddress'

**Comment by jefffhaynes** [comment]
Sorry, I only have my phone here. Can you construct a NodeAddress from a LongAddress?


________________________________

**Comment by koopermark** [comment]
I added the following
`            XBeeNode localNode = controller.Local;
            
            NodeAddress BroadcastNodeAddress = new NodeAddress(LongAddress.Broadcast);
            Debug.WriteLine(BroadcastNodeAddress);

            try
            {
                await controller.GetNodeAsync(BroadcastNodeAddress);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }

            try
            {
                await localNode.TransmitDataAsync(Encoding.UTF8.GetBytes("Hello!"));
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
`
and get the following output
000000000000FFFF, FFFE
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.ni.dll
Can't send data to local device.

**Comment by jefffhaynes** [comment]
You need to use the returned node.

var remoteNode =  await controller.GetNodeAsync(BroadcastNodeAddress);

remoteNode.Transmit...


________________________________

**Comment by koopermark** [comment]
ok so using the following
            `NodeAddress BroadcastNodeAddress = new NodeAddress(LongAddress.Broadcast);        
            Debug.WriteLine(BroadcastNodeAddress);

            var remoteNode = await controller.GetNodeAsync(BroadcastNodeAddress);
            Debug.WriteLine(remoteNode);

            try
            {
                await remoteNode.TransmitDataAsync(Encoding.UTF8.GetBytes("Hello!"));
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        Debug.WriteLine("Sent I guess");`

I get the following
Connection Done
000000000000FFFF, FFFE
XBee.Devices.XBeeSeries2
Sent I guess

There is noting showing in XCTU as being received so i'm not sure if it did - but there are no errors

**Comment by koopermark** [comment]
scratch that last comment, reloaded XCTU and its working :-) :-)
thank you soooo much

A face full of smiles and a tear in the eye

**Comment by jefffhaynes** [comment]
Phew. Glad to hear it :)

________________________________

**Comment by koopermark** [comment]
How can I repay your effort - buy you a beer / Pizza - PayPal donation

**Comment by jefffhaynes** [comment]
Ha, thanks. No need, it’s an enjoyable hobby for me.

I’ll probably look at making broadcast a little easier too. Seems confusing as designed.


________________________________

**Comment by koopermark** [comment]
Thanks again, its very much appreciated.
