### ISSUE TITLE
What happened to XBee? Any new versions supported with .NET 9.0? 

### ISSUE THREAD

**Issue by LarryChiem** [jefffhaynes/XBee#68]

**Comment by jefffhaynes** [comment]
I'm afraid I don't have much time these days for it but if you want to submit a PR I'll review!

**Comment by kvertner** [comment]
@jefffhaynes I work with LarryChiem.  I've started the process of upgrading all of the projects to .NET 8.  Everything is looking good with the exception of the Xbee.Universal project.  I don't have a lot of experience with UWP projects, tried a few things...but just keep running into a brick wall.  If I submit a PR with what I have so far, do you think you could take a look?

**Comment by kvertner** [comment]
It looks like the issues with the Xbee.Universal project revolve around not being able to find the Windows 10 APIs after the upgrade.

**Comment by jefffhaynes** [comment]
Yeah the UWP stuff is weird. I can look at it.

**Comment by kvertner** [comment]
@jefffhaynes Thanks again for being willing to take a look.  The PR is up there.  Any estimates on when you might be able to take a look?

**Comment by jefffhaynes** [comment]
Did you see my comment on the PR?

**Comment by kvertner** [comment]
Looking now!  Thanks

**Comment by kvertner** [comment]
@jefffhaynes Thanks for your help in getting the project updated!  Any idea when we could see it available in NuGet?

**Comment by jefffhaynes** [comment]
I updated XBee.Core and created XBee.Classic with no UWP support.

**Comment by LarryChiem** [comment]
![image](https://github.com/user-attachments/assets/8b27d6c1-b1a6-4c38-9131-7806d567885c)
I'm still seeing that XBee 5.3.3 hasn't been updated to support net8.0. Will this also be updated @jefffhaynes ?

**Comment by jefffhaynes** [comment]
I wasn't planning on it. What are you trying to do that XBee.Classic won't do?
